import { useEffect, useState } from 'react'
import { BarChart3, Check, Library, LoaderCircle, Play, Bookmark, Pause, XCircle, RefreshCw } from 'lucide-react'
import { getAdminStats } from '../services/adminService'
import { readableError } from '../utils/format'

const count=value=>Number(value||0).toLocaleString()

export default function AdminAnime() {
  const [stats,setStats]=useState(null)
  const [loading,setLoading]=useState(true)
  const [error,setError]=useState('')
  const load=async()=>{setLoading(true);setError('');try{setStats(await getAdminStats())}catch(cause){setError(readableError(cause))}finally{setLoading(false)}}
  useEffect(()=>{load()},[])
  const totals=[['Unique anime titles','unique_anime_titles',Library],['All watchlist entries','total_watchlist_entries',Library],['Currently watching','currently_watching',Play],['Plan to watch','plan_to_watch',Bookmark],['Completed','completed_anime',Check],['On hold','on_hold',Pause],['Dropped','dropped',XCircle]]
  return <div className="admin-page"><header className="admin-page-heading"><div><span className="admin-eyebrow">AGGREGATE INSIGHTS</span><h1>Anime &amp; watchlists</h1><p>Collection trends across the platform, without exposing private lists.</p></div><button className="outline-btn" onClick={load} disabled={loading}><RefreshCw size={14} className={loading?'spin':''}/> Refresh</button></header>{error&&<div className="admin-error" role="alert">{error}<button onClick={load}>Retry</button></div>}<section className="admin-anime-count-grid">{totals.map(([label,key,Icon])=><article className="admin-user-count-card" key={key}><span><Icon size={16}/>{label}</span><strong>{loading?'—':count(stats?.[key])}</strong></article>)}</section><div className="admin-dashboard-grid"><section className="admin-panel"><header className="admin-panel-heading"><div><span className="admin-eyebrow">MOST ADDED</span><h2>Popular anime</h2></div><BarChart3 size={18}/></header>{loading?<div className="admin-panel-loading"><LoaderCircle className="spin" size={18}/> Loading analytics…</div>:stats?.most_added_anime?.length?<div className="admin-rank-list">{stats.most_added_anime.map((row,index)=><div className="admin-rank-row" key={row.title}><span>{String(index+1).padStart(2,'0')}</span><strong>{row.title}</strong><b>{count(row.entries)} entries</b></div>)}</div>:<div className="admin-empty"><Library size={22}/><strong>No watchlist data yet</strong></div>}</section><section className="admin-panel"><header className="admin-panel-heading"><div><span className="admin-eyebrow">MOST COMPLETED</span><h2>Finished anime</h2></div><Check size={18}/></header>{loading?<div className="admin-panel-loading">Loading analytics…</div>:stats?.most_completed_anime?.length?<div className="admin-rank-list">{stats.most_completed_anime.map((row,index)=><div className="admin-rank-row" key={row.title}><span>{String(index+1).padStart(2,'0')}</span><strong>{row.title}</strong><b>{count(row.entries)} completed</b></div>)}</div>:<div className="admin-empty"><Check size={22}/><strong>No completed anime yet</strong></div>}</section></div><section className="admin-privacy-note"><Library size={16}/><p>Anime entries belong to individual users and remain protected by their existing RLS policies. These statistics are server-generated aggregates; the admin UI does not fetch individual watchlist rows.</p></section></div>
}
